name: Build EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Checkout source
      uses: actions/checkout@v4

    - name: Download AutoHotkey v2
      run: |
        curl -L -o ahk.zip https://www.autohotkey.com/download/ahk-v2.zip
        powershell Expand-Archive ahk.zip -DestinationPath ahk

    - name: Compile EXE
      run: |
        ahk\AutoHotkey64.exe /ErrorStdOut ^
        ahk\Compiler\Ahk2Exe.ahk ^
        /in NetSpeedTaskbar.ahk ^
        /out NetSpeedTaskbar.exe

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: NetSpeedTaskbar
        path: NetSpeedTaskbar.exe
