name: Build EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile AutoHotkey script
      uses: benmusson/ahk2exe-action@v1
      with:
        in: NetSpeedTaskbar.ahk
        out: NetSpeedTaskbar.exe

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: NetSpeedTaskbar
        path: NetSpeedTaskbar.exe
